'use strict';

const path = require('path');

/** Valid project ids: lowercase slugs generated by the store. */
const PROJECT_ID_RE = /^[a-z0-9-]{1,80}$/;

/**
 * Resolve a user-supplied relative path under a base directory.
 * Returns the absolute path, or null if the input escapes the base
 * (path traversal, absolute paths, drive letters).
 */
function safeJoin(base, rel) {
  if (rel == null) return null;
  const clean = String(rel).replace(/\\/g, '/').replace(/^\/+/, '');
  if (/^[a-zA-Z]:/.test(clean)) return null;
  const full = path.resolve(base, clean);
  if (full !== base && !full.startsWith(base + path.sep)) return null;
  return full;
}

/**
 * Console commands are restricted to local runtimes. This is a coarse
 * allowlist, not a sandbox — Replica is a personal localhost tool and the
 * command runs with the user's own privileges either way.
 */
const COMMAND_ALLOW_RE = /^(node|python|python3|py|pip|pip3|npm|npx)(\s|$)/;

// Commands run through a shell, so chaining and redirection would let an
// allowlisted prefix smuggle in anything ("node -v & curl ..."). Reject the
// metacharacters outright rather than trying to parse shell syntax.
const SHELL_META_RE = /[;&|<>`\r\n]|\$\(/;

function isAllowedCommand(cmd) {
  const c = String(cmd).trim();
  return COMMAND_ALLOW_RE.test(c) && !SHELL_META_RE.test(c);
}

module.exports = { safeJoin, isAllowedCommand, PROJECT_ID_RE };
